/* Room Planner — script.js | Phase 1-7 */
(function(){ 'use strict';
const canvas=document.getElementById('room-canvas'),ctx=canvas.getContext('2d');
const COLOURS=[{hex:'#ffffff',label:'White'},{hex:'#f0f0f0',label:'Light Grey'},{hex:'#4a4a4a',label:'Dark Grey'},{hex:'#e74c3c',label:'Red'},{hex:'#e67e22',label:'Orange'},{hex:'#f1c40f',label:'Yellow'},{hex:'#2ecc71',label:'Green'},{hex:'#3498db',label:'Blue'},{hex:'#9b59b6',label:'Purple'},{hex:'#e91e8c',label:'Pink'},{hex:'#795548',label:'Brown'},{hex:'#000000',label:'Black'}];
let zoom=1,panX=0,panY=0;
const MIN_ZOOM=0.2,MAX_ZOOM=5;
let isPanning=false,panStartX=0,panStartY=0,panOriginX=0,panOriginY=0;
let editMode=false,room=null,shapes=[],labels=[],strokes=[];
let selectedShape=null,selectedLabel=null;
let activeShapeTool=null,textToolActive=false,drawToolActive=false;
let drag=null,editingLabel=null;
let cornerHandles=[],edgeHandles=[];
let isDrawing=false,currentStroke=null;
let drawColour='#222222',drawSize=4,eraserActive=false;
let hasUnsavedChanges=false;
const ROOM_HANDLE_R=7,SEL_HANDLE_R=6,ROT_HANDLE_R=6,ROT_OFFSET=28,MIN_SHAPE_SIZE=20;
const SHAPE_DEFAULTS={square:{w:80,h:80},rect:{w:120,h:70},circle:{w:80,h:80}};

function init(){
  resizeCanvas();
    window.addEventListener('resize',onWindowResize);
      canvas.addEventListener('pointerdown',onPointerDown);
        canvas.addEventListener('pointermove',onPointerMove);
          canvas.addEventListener('pointerup',onPointerUp);
            canvas.addEventListener('pointerleave',onPointerUp);
              canvas.addEventListener('wheel',onWheel,{passive:false});
                document.addEventListener('keydown',onKeyDown);
                  document.getElementById('btn-edit-room').addEventListener('click',toggleEditMode);
                    document.getElementById('btn-new').addEventListener('click',newRoom);
                      document.getElementById('btn-save').addEventListener('click',saveRoom);
                        document.getElementById('btn-print').addEventListener('click',printRoom);
                          document.getElementById('btn-square').addEventListener('click',()=>activateShapeTool('square'));
                            document.getElementById('btn-rect').addEventListener('click',()=>activateShapeTool('rect'));
                              document.getElementById('btn-circle').addEventListener('click',()=>activateShapeTool('circle'));
                                document.getElementById('btn-zoom-in').addEventListener('click',()=>zoomBy(1.25));
                                  document.getElementById('btn-zoom-out').addEventListener('click',()=>zoomBy(0.8));
                                    document.getElementById('btn-zoom-reset').addEventListener('click',resetZoom);
                                      document.getElementById('btn-delete-shape').addEventListener('click',deleteSelected);
                                        document.getElementById('btn-add-text').addEventListener('click',activateTextTool);
                                          document.getElementById('btn-draw').addEventListener('click',activateDrawTool);
                                            document.getElementById('btn-eraser').addEventListener('click',activateEraser);
                                              document.getElementById('btn-clear-drawing').addEventListener('click',clearStrokes);
                                                const drawColourEl=document.getElementById('draw-colour');
                                                  const drawSizeEl=document.getElementById('draw-size');
                                                    if(drawColourEl) drawColourEl.addEventListener('input',e=>{drawColour=e.target.value;eraserActive=false;});
                                                      if(drawSizeEl) drawSizeEl.addEventListener('input',e=>{drawSize=parseInt(e.target.value)||4;document.getElementById('draw-size-label').textContent=e.target.value+'px';});
                                                        buildColourPalette();
                                                          wireTextControls();
                                                            loadRoom();
                                                              draw();
                                                              }

                                                              function markUnsaved(){
                                                                if(!hasUnsavedChanges){
                                                                    hasUnsavedChanges=true;
                                                                        const btn=document.getElementById('btn-save');
                                                                            if(btn&&btn.textContent==='Save'){btn.textContent='Save *';btn.style.fontWeight='700';}
                                                                              }
                                                                              }

                                                                              function resetSaveBtn(){
                                                                                hasUnsavedChanges=false;
                                                                                  const btn=document.getElementById('btn-save');
                                                                                    if(btn){btn.textContent='Save';btn.style.color='';btn.style.fontWeight='';btn.style.borderColor='';}
                                                                                    }

                                                                                    function resizeCanvas(){const area=document.getElementById('canvas-area');canvas.width=area.clientWidth;canvas.height=area.clientHeight;if(!room)room=defaultRoom(canvas.width,canvas.height);draw();}
                                                                                    function onWindowResize(){resizeCanvas();}
                                                                                    function defaultRoom(w,h){const m=32;return[{x:m,y:m},{x:w-m,y:m},{x:w-m,y:h-m},{x:m,y:h-m}];}
                                                                                    function cornersToFractions(c,w,h){return c.map(p=>({fx:p.x/w,fy:p.y/h}));}
                                                                                    function fractionsToCorners(f,w,h){return f.map(p=>({x:p.fx*w,y:p.fy*h}));}
                                                                                    function zoomBy(factor,cx,cy){cx=cx??canvas.width/2;cy=cy??canvas.height/2;const nz=Math.min(MAX_ZOOM,Math.max(MIN_ZOOM,zoom*factor)),sc=nz/zoom;panX=cx-sc*(cx-panX);panY=cy-sc*(cy-panY);zoom=nz;updateZoomLabel();draw();}
                                                                                    function resetZoom(){zoom=1;panX=0;panY=0;updateZoomLabel();draw();}
                                                                                    function updateZoomLabel(){const el=document.getElementById('zoom-label');if(el)el.textContent=Math.round(zoom*100)+'%';}
                                                                                    function onWheel(e){e.preventDefault();const r=canvas.getBoundingClientRect();zoomBy(e.deltaY<0?1.1:0.9,(e.clientX-r.left)*(canvas.width/r.width),(e.clientY-r.top)*(canvas.height/r.height));}
                                                                                    function toWorld(px,py){return{x:(px-panX)/zoom,y:(py-panY)/zoom};}
                                                                                    function toCanvas(wx,wy){return{x:wx*zoom+panX,y:wy*zoom+panY};}
                                                                                    function getRawPos(e){const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height,src=e.touches?e.touches[0]:e;return{x:(src.clientX-r.left)*sx,y:(src.clientY-r.top)*sy};}

                                                                                    function buildColourPalette(){const grid=document.getElementById('colour-grid');if(!grid)return;grid.innerHTML='';COLOURS.forEach(c=>{const btn=document.createElement('button');btn.className='colour-swatch';btn.title=c.label;btn.style.background=c.hex;btn.style.border=(c.hex==='#ffffff'||c.hex==='#f0f0f0'||c.hex==='#f1c40f')?'2px solid #ccc':'2px solid transparent';btn.addEventListener('click',()=>applyColour(c.hex));grid.appendChild(btn);});}
                                                                                    function applyColour(hex){if(selectedShape){selectedShape.fill=hex;updateColourUI();markUnsaved();draw();}}
                                                                                    function updateColourUI(){const grid=document.getElementById('colour-grid');if(!grid)return;grid.querySelectorAll('.colour-swatch').forEach((btn,i)=>{const active=selectedShape&&COLOURS[i].hex===selectedShape.fill;btn.classList.toggle('active',active);btn.style.border=active?'2px solid #1a73e8':(COLOURS[i].hex==='#ffffff'||COLOURS[i].hex==='#f0f0f0'||COLOURS[i].hex==='#f1c40f')?'2px solid #ccc':'2px solid transparent';});}

                                                                                    function buildRoomHandles(){cornerHandles=room.map((c,i)=>({x:c.x,y:c.y,index:i}));edgeHandles=room.map((c,i)=>{const n=room[(i+1)%4];return{x:(c.x+n.x)/2,y:(c.y+n.y)/2,index:i};});}
                                                                                    function activateShapeTool(type){clearAllTools();activeShapeTool=type;selectedShape=null;selectedLabel=null;updateSelectionUI();['btn-square','btn-rect','btn-circle'].forEach(id=>document.getElementById(id).classList.remove('active'));document.getElementById({square:'btn-square',rect:'btn-rect',circle:'btn-circle'}[type]).classList.add('active');canvas.style.cursor='crosshair';draw();}
                                                                                    function activateTextTool(){clearAllTools();textToolActive=true;selectedShape=null;selectedLabel=null;updateSelectionUI();document.getElementById('btn-add-text').classList.add('active');canvas.style.cursor='text';draw();}
                                                                                    function activateDrawTool(){clearAllTools();drawToolActive=true;eraserActive=false;document.getElementById('btn-draw').classList.add('active');document.getElementById('btn-eraser').classList.remove('active');canvas.style.cursor='crosshair';updateDrawUI();draw();}
                                                                                    function activateEraser(){clearAllTools();drawToolActive=true;eraserActive=true;document.getElementById('btn-eraser').classList.add('active');document.getElementById('btn-draw').classList.remove('active');canvas.style.cursor='cell';updateDrawUI();draw();}
                                                                                    function clearAllTools(){activeShapeTool=null;textToolActive=false;drawToolActive=false;eraserActive=false;['btn-square','btn-rect','btn-circle','btn-add-text','btn-draw','btn-eraser'].forEach(id=>{const el=document.getElementById(id);if(el)el.classList.remove('active');});canvas.style.cursor='default';}
                                                                                    function clearStrokes(){strokes=[];markUnsaved();draw();}
                                                                                    function updateDrawUI(){const section=document.getElementById('draw-section');if(section)section.style.display=drawToolActive?'block':'none';}

                                                                                    function addShape(type,cx,cy){const d=SHAPE_DEFAULTS[type];const s={id:Date.now(),type,x:cx-d.w/2,y:cy-d.h/2,w:d.w,h:d.h,angle:0,fill:'#ffffff'};shapes.push(s);selectedShape=s;selectedLabel=null;markUnsaved();updateSelectionUI();return s;}
                                                                                    function clampShapeToRoom(s){const b=roomBounds();s.x=Math.max(b.left,Math.min(b.right-s.w,s.x));s.y=Math.max(b.top,Math.min(b.bottom-s.h,s.y));}
                                                                                    function roomBounds(){const xs=room.map(c=>c.x),ys=room.map(c=>c.y);return{left:Math.min(...xs),top:Math.min(...ys),right:Math.max(...xs),bottom:Math.max(...ys)};}

                                                                                    function addLabel(x,y){const lbl={id:Date.now(),x,y,text:'Label',fontSize:16,colour:'#222222',bold:false};labels.push(lbl);selectedLabel=lbl;selectedShape=null;markUnsaved();updateSelectionUI();clearAllTools();openLabelEditor(lbl);return lbl;}
                                                                                    function openLabelEditor(lbl){editingLabel=lbl;const old=document.getElementById('label-editor');if(old)old.remove();const sc=toCanvas(lbl.x,lbl.y);const area=document.getElementById('canvas-area');const cr=canvas.getBoundingClientRect();const input=document.createElement('input');input.type='text';input.id='label-editor';input.value=lbl.text;input.style.cssText='position:absolute;left:'+(sc.x*(cr.width/canvas.width)-4)+'px;top:'+(sc.y*(cr.height/canvas.height)-lbl.fontSize*zoom-4)+'px;font-size:'+(lbl.fontSize*zoom)+'px;font-weight:'+(lbl.bold?'bold':'normal')+';color:'+lbl.colour+';background:rgba(255,255,255,0.92);border:1px dashed #1a73e8;border-radius:3px;padding:2px 6px;outline:none;min-width:80px;z-index:100;font-family:inherit;';area.appendChild(input);input.focus();input.select();input.addEventListener('input',()=>{lbl.text=input.value||'?';markUnsaved();draw();});input.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key==='Escape'){closeLabelEditor();e.preventDefault();}e.stopPropagation();});input.addEventListener('blur',()=>closeLabelEditor());}
                                                                                    function closeLabelEditor(){const el=document.getElementById('label-editor');if(el)el.remove();if(editingLabel&&(!editingLabel.text||!editingLabel.text.trim())){labels=labels.filter(l=>l!==editingLabel);if(selectedLabel===editingLabel)selectedLabel=null;}editingLabel=null;updateSelectionUI();draw();}

                                                                                    function wireTextControls(){const sizeEl=document.getElementById('text-size'),boldEl=document.getElementById('text-bold'),colEl=document.getElementById('text-colour'),editEl=document.getElementById('btn-edit-label');if(sizeEl)sizeEl.addEventListener('input',()=>{if(selectedLabel){selectedLabel.fontSize=parseInt(sizeEl.value)||16;markUnsaved();draw();}});if(boldEl)boldEl.addEventListener('change',()=>{if(selectedLabel){selectedLabel.bold=boldEl.checked;markUnsaved();draw();}});if(colEl)colEl.addEventListener('input',()=>{if(selectedLabel){selectedLabel.colour=colEl.value;markUnsaved();draw();}});if(editEl)editEl.addEventListener('click',()=>{if(selectedLabel)openLabelEditor(selectedLabel);});}

                                                                                    function updateSelectionUI(){const del=document.getElementById('btn-delete-shape'),col=document.getElementById('colour-section'),textSel=document.getElementById('text-selected-section');if(del)del.style.display=(selectedShape||selectedLabel)?'block':'none';if(col)col.style.display=selectedShape?'block':'none';if(textSel)textSel.style.display=selectedLabel?'block':'none';updateColourUI();if(selectedLabel){const sizeEl=document.getElementById('text-size'),boldEl=document.getElementById('text-bold'),colEl=document.getElementById('text-colour');if(sizeEl)sizeEl.value=selectedLabel.fontSize;if(boldEl)boldEl.checked=selectedLabel.bold;if(colEl)colEl.value=selectedLabel.colour;}}

                                                                                    function deleteSelected(){if(selectedShape){shapes=shapes.filter(s=>s!==selectedShape);selectedShape=null;}if(selectedLabel){labels=labels.filter(l=>l!==selectedLabel);selectedLabel=null;}markUnsaved();updateSelectionUI();draw();}
                                                                                    function onKeyDown(e){if(e.key==='Delete'||e.key==='Backspace'){if(document.activeElement.tagName==='INPUT'||document.activeElement.tagName==='TEXTAREA')return;deleteSelected();}if(e.key==='Escape')closeLabelEditor();}

                                                                                    function getSelHandles(s){const cx=s.x+s.w/2,cy=s.y+s.h/2,hw=s.w/2,hh=s.h/2,cos=Math.cos(s.angle),sin=Math.sin(s.angle);const corners=[{lx:-hw,ly:-hh,index:0},{lx:hw,ly:-hh,index:1},{lx:hw,ly:hh,index:2},{lx:-hw,ly:hh,index:3}].map(({lx,ly,index})=>({x:cx+lx*cos-ly*sin,y:cy+lx*sin+ly*cos,index}));return{corners,rotate:{x:cx-Math.sin(s.angle)*(-(hh+ROT_OFFSET)),y:cy+Math.cos(s.angle)*(-(hh+ROT_OFFSET))}};}
                                                                                    function hitCircleW(wx,wy,hx,hy,r){const sr=(r+4)/zoom,dx=wx-hx,dy=wy-hy;return dx*dx+dy*dy<=sr*sr;}
                                                                                    function hitRoomHandle(wx,wy,handles){for(let i=handles.length-1;i>=0;i--)if(hitCircleW(wx,wy,handles[i].x,handles[i].y,ROOM_HANDLE_R))return i;return -1;}
                                                                                    function hitSelHandle(wx,wy){if(!selectedShape)return null;const h=getSelHandles(selectedShape);if(hitCircleW(wx,wy,h.rotate.x,h.rotate.y,ROT_HANDLE_R))return{type:'rotate'};for(const c of h.corners)if(hitCircleW(wx,wy,c.x,c.y,SEL_HANDLE_R))return{type:'resize',index:c.index};return null;}
                                                                                    function hitShape(wx,wy){for(let i=shapes.length-1;i>=0;i--){const s=shapes[i],cx=s.x+s.w/2,cy=s.y+s.h/2,cos=Math.cos(-s.angle),sin=Math.sin(-s.angle),lx=(wx-cx)*cos-(wy-cy)*sin,ly=(wx-cx)*sin+(wy-cy)*cos;if(s.type==='circle'){if((lx/(s.w/2))*(lx/(s.w/2))+(ly/(s.h/2))*(ly/(s.h/2))<=1)return s;}else{if(lx>=-s.w/2&&lx<=s.w/2&&ly>=-s.h/2&&ly<=s.h/2)return s;}}return null;}
                                                                                    function hitLabel(wx,wy){for(let i=labels.length-1;i>=0;i--){const l=labels[i],approxW=l.text.length*l.fontSize*0.6+12,approxH=l.fontSize+8;if(wx>=l.x-6&&wx<=l.x+approxW&&wy>=l.y-approxH&&wy<=l.y+6)return l;}return null;}

                                                                                    function onPointerDown(e){
                                                                                      e.preventDefault();canvas.setPointerCapture(e.pointerId);
                                                                                        if(editingLabel){closeLabelEditor();return;}
                                                                                          const raw=getRawPos(e),{x,y}=toWorld(raw.x,raw.y);
                                                                                            if(drawToolActive){isDrawing=true;currentStroke={points:[{x,y}],colour:eraserActive?'#e8e8e8':drawColour,size:eraserActive?drawSize*3:drawSize,eraser:eraserActive};strokes.push(currentStroke);return;}
                                                                                              if(activeShapeTool){const s=addShape(activeShapeTool,x,y);clampShapeToRoom(s);clearAllTools();draw();return;}
                                                                                                if(textToolActive){addLabel(x,y);draw();return;}
                                                                                                  if(e.button===1||e.altKey){isPanning=true;panStartX=raw.x;panStartY=raw.y;panOriginX=panX;panOriginY=panY;canvas.style.cursor='grabbing';return;}
                                                                                                    if(editMode){const ci=hitRoomHandle(x,y,cornerHandles);if(ci!==-1){drag={type:'corner',index:cornerHandles[ci].index,startX:x,startY:y,origRoom:room.map(c=>({...c}))};return;}const ei=hitRoomHandle(x,y,edgeHandles);if(ei!==-1){drag={type:'edge',index:edgeHandles[ei].index,startX:x,startY:y,origRoom:room.map(c=>({...c}))};return;}}
                                                                                                      const sh=hitSelHandle(x,y);
                                                                                                        if(sh){const s=selectedShape;if(sh.type==='rotate'){const cx=s.x+s.w/2,cy=s.y+s.h/2;drag={type:'rotate',shape:s,startAngle:s.angle,startAtan:Math.atan2(y-cy,x-cx)};}else{const h=getSelHandles(s),opp=h.corners[(sh.index+2)%4];drag={type:'resize',shape:s,cornerIndex:sh.index,startX:x,startY:y,origX:s.x,origY:s.y,origW:s.w,origH:s.h,origAngle:s.angle,anchorX:opp.x,anchorY:opp.y};}return;}
                                                                                                          const hs=hitShape(x,y);if(hs){selectedShape=hs;selectedLabel=null;shapes=shapes.filter(s=>s!==hs);shapes.push(hs);drag={type:'shape',shape:hs,startX:x,startY:y,origX:hs.x,origY:hs.y};updateSelectionUI();draw();return;}
                                                                                                            const hl=hitLabel(x,y);if(hl){selectedLabel=hl;selectedShape=null;drag={type:'label',label:hl,startX:x,startY:y,origX:hl.x,origY:hl.y};updateSelectionUI();draw();return;}
                                                                                                              selectedShape=null;selectedLabel=null;updateSelectionUI();
                                                                                                                isPanning=true;panStartX=raw.x;panStartY=raw.y;panOriginX=panX;panOriginY=panY;canvas.style.cursor='grabbing';draw();
                                                                                                                }

                                                                                                                function onPointerMove(e){
                                                                                                                  const raw=getRawPos(e),{x,y}=toWorld(raw.x,raw.y);
                                                                                                                    if(drawToolActive&&isDrawing&&currentStroke){currentStroke.points.push({x,y});markUnsaved();draw();return;}
                                                                                                                      if(isPanning){panX=panOriginX+(raw.x-panStartX);panY=panOriginY+(raw.y-panStartY);canvas.style.cursor='grabbing';draw();return;}
                                                                                                                        if(!drag){
                                                                                                                            if(activeShapeTool){canvas.style.cursor='crosshair';return;}
                                                                                                                                if(textToolActive){canvas.style.cursor='text';return;}
                                                                                                                                    if(drawToolActive){canvas.style.cursor=eraserActive?'cell':'crosshair';return;}
                                                                                                                                        const sh=hitSelHandle(x,y);if(sh){canvas.style.cursor=sh.type==='rotate'?'grab':'nwse-resize';return;}
                                                                                                                                            if(editMode){canvas.style.cursor=(hitRoomHandle(x,y,cornerHandles)!==-1||hitRoomHandle(x,y,edgeHandles)!==-1)?'grab':'default';}
                                                                                                                                                else{canvas.style.cursor=(hitShape(x,y)||hitLabel(x,y))?'grab':'default';}
                                                                                                                                                    return;
                                                                                                                                                      }
                                                                                                                                                        e.preventDefault();
                                                                                                                                                          const dx=x-drag.startX,dy=y-drag.startY;
                                                                                                                                                            if(drag.type==='corner'){room[drag.index]={x:drag.origRoom[drag.index].x+dx,y:drag.origRoom[drag.index].y+dy};markUnsaved();}
                                                                                                                                                              else if(drag.type==='edge'){const i=drag.index,n=(i+1)%4,horiz=Math.abs(drag.origRoom[n].x-drag.origRoom[i].x)>Math.abs(drag.origRoom[n].y-drag.origRoom[i].y);if(horiz){room[i]={x:drag.origRoom[i].x,y:drag.origRoom[i].y+dy};room[n]={x:drag.origRoom[n].x,y:drag.origRoom[n].y+dy};}else{room[i]={x:drag.origRoom[i].x+dx,y:drag.origRoom[i].y};room[n]={x:drag.origRoom[n].x+dx,y:drag.origRoom[n].y};}markUnsaved();}
                                                                                                                                                                else if(drag.type==='shape'){drag.shape.x=drag.origX+dx;drag.shape.y=drag.origY+dy;clampShapeToRoom(drag.shape);markUnsaved();}
                                                                                                                                                                  else if(drag.type==='rotate'){const s=drag.shape,cx=s.x+s.w/2,cy=s.y+s.h/2;s.angle=drag.startAngle+(Math.atan2(y-cy,x-cx)-drag.startAtan);markUnsaved();}
                                                                                                                                                                    else if(drag.type==='resize'){const s=drag.shape,cos=Math.cos(-s.angle),sin=Math.sin(-s.angle),wxm=x-drag.anchorX,wym=y-drag.anchorY,lxm=wxm*cos-wym*sin,lym=wxm*sin+wym*cos,ci=drag.cornerIndex,signX=(ci===0||ci===3)?-1:1,signY=(ci===0||ci===1)?-1:1;s.w=Math.max(MIN_SHAPE_SIZE,Math.abs(lxm));s.h=Math.max(MIN_SHAPE_SIZE,Math.abs(lym));const cosA=Math.cos(s.angle),sinA=Math.sin(s.angle),oppLx=-signX*s.w/2,oppLy=-signY*s.h/2;s.x=drag.anchorX+(-oppLx*cosA+oppLy*sinA)-s.w/2;s.y=drag.anchorY+(-oppLx*sinA-oppLy*cosA)-s.h/2;markUnsaved();}
                                                                                                                                                                      else if(drag.type==='label'){drag.label.x=drag.origX+dx;drag.label.y=drag.origY+dy;markUnsaved();}
                                                                                                                                                                        draw();
                                                                                                                                                                        }

                                                                                                                                                                        function onPointerUp(){if(drawToolActive&&isDrawing){isDrawing=false;currentStroke=null;return;}if(isPanning){isPanning=false;canvas.style.cursor='default';}drag=null;}

                                                                                                                                                                        function draw(){
                                                                                                                                                                          ctx.clearRect(0,0,canvas.width,canvas.height);
                                                                                                                                                                            ctx.save();ctx.translate(panX,panY);ctx.scale(zoom,zoom);
                                                                                                                                                                              drawRoom();shapes.forEach(drawShape);drawStrokes();labels.forEach(drawLabel);
                                                                                                                                                                                if(editMode){buildRoomHandles();drawRoomHandlesOnCanvas();}
                                                                                                                                                                                  ctx.restore();
                                                                                                                                                                                    if(selectedShape)drawSelHandles(selectedShape);
                                                                                                                                                                                      if(selectedLabel)drawLabelSelection(selectedLabel);
                                                                                                                                                                                      }

                                                                                                                                                                                      function drawRoom(){if(!room)return;ctx.beginPath();ctx.moveTo(room[0].x,room[0].y);for(let i=1;i<4;i++)ctx.lineTo(room[i].x,room[i].y);ctx.closePath();ctx.fillStyle='#ffffff';ctx.fill();ctx.strokeStyle='#222222';ctx.lineWidth=3/zoom;ctx.lineJoin='round';ctx.stroke();}
                                                                                                                                                                                      function drawShape(s){const cx=s.x+s.w/2,cy=s.y+s.h/2;ctx.save();ctx.translate(cx,cy);ctx.rotate(s.angle);ctx.fillStyle=s.fill||'#ffffff';ctx.strokeStyle='#222222';ctx.lineWidth=2/zoom;if(s.type==='circle'){ctx.beginPath();ctx.ellipse(0,0,s.w/2,s.h/2,0,0,Math.PI*2);ctx.fill();ctx.stroke();}else{ctx.beginPath();ctx.rect(-s.w/2,-s.h/2,s.w,s.h);ctx.fill();ctx.stroke();}ctx.restore();}
                                                                                                                                                                                      function drawStrokes(){strokes.forEach(stroke=>{if(!stroke.points||stroke.points.length<2)return;ctx.save();ctx.strokeStyle=stroke.colour;ctx.lineWidth=stroke.size/zoom;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(stroke.points[0].x,stroke.points[0].y);for(let i=1;i<stroke.points.length;i++)ctx.lineTo(stroke.points[i].x,stroke.points[i].y);ctx.stroke();ctx.restore();});}
                                                                                                                                                                                      function drawLabel(l){ctx.save();ctx.font=(l.bold?'bold ':'')+l.fontSize+'px -apple-system,BlinkMacSystemFont,\'Segoe UI\',sans-serif';ctx.fillStyle=l.colour||'#222222';ctx.textBaseline='alphabetic';ctx.shadowColor='rgba(255,255,255,0.8)';ctx.shadowBlur=3;ctx.fillText(l.text,l.x,l.y);ctx.restore();}
                                                                                                                                                                                      function drawLabelSelection(l){const sc=toCanvas(l.x,l.y);ctx.save();ctx.font=(l.bold?'bold ':'')+l.fontSize*zoom+'px -apple-system,BlinkMacSystemFont,\'Segoe UI\',sans-serif';const metrics=ctx.measureText(l.text),w=metrics.width+12,h=l.fontSize*zoom+10;ctx.strokeStyle='#1a73e8';ctx.lineWidth=1.5;ctx.setLineDash([5,3]);ctx.strokeRect(sc.x-6,sc.y-l.fontSize*zoom-4,w,h);ctx.setLineDash([]);ctx.restore();}
                                                                                                                                                                                      function drawRoomHandlesOnCanvas(){const r=ROOM_HANDLE_R/zoom;cornerHandles.forEach(h=>drawWorldCircle(h.x,h.y,r,'#1a73e8','#fff'));edgeHandles.forEach(h=>drawWorldCircle(h.x,h.y,r,'#0d9488','#fff'));}
                                                                                                                                                                                      function drawWorldCircle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=2/zoom;ctx.stroke();}
                                                                                                                                                                                      function drawSelHandles(s){const h=getSelHandles(s),csc=toCanvas(s.x+s.w/2,s.y+s.h/2);ctx.save();ctx.translate(csc.x,csc.y);ctx.rotate(s.angle);ctx.strokeStyle='#1a73e8';ctx.lineWidth=1.5;ctx.setLineDash([5,3]);if(s.type==='circle'){ctx.beginPath();ctx.ellipse(0,0,s.w/2*zoom+6,s.h/2*zoom+6,0,0,Math.PI*2);ctx.stroke();}else{ctx.strokeRect(-s.w/2*zoom-5,-s.h/2*zoom-5,s.w*zoom+10,s.h*zoom+10);}ctx.setLineDash([]);ctx.restore();h.corners.forEach(c=>{const sc=toCanvas(c.x,c.y);drawScreenCircle(sc.x,sc.y,SEL_HANDLE_R,'#1a73e8','#fff');});const sr=toCanvas(h.rotate.x,h.rotate.y),tcw={x:s.x+s.w/2-Math.sin(s.angle)*(-s.h/2),y:s.y+s.h/2+Math.cos(s.angle)*(-s.h/2)},tc=toCanvas(tcw.x,tcw.y);ctx.beginPath();ctx.moveTo(tc.x,tc.y);ctx.lineTo(sr.x,sr.y);ctx.strokeStyle='#1a73e8';ctx.lineWidth=1.5;ctx.setLineDash([3,2]);ctx.stroke();ctx.setLineDash([]);drawScreenCircle(sr.x,sr.y,ROT_HANDLE_R,'#fff','#1a73e8');ctx.save();ctx.translate(sr.x,sr.y);ctx.rotate(s.angle);ctx.strokeStyle='#1a73e8';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,3,-Math.PI*0.7,Math.PI*0.7);ctx.stroke();ctx.restore();}
                                                                                                                                                                                      function drawScreenCircle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}

                                                                                                                                                                                      function toggleEditMode(){editMode=!editMode;clearAllTools();document.getElementById('btn-edit-room').classList.toggle('active',editMode);draw();}

                                                                                                                                                                                      /* Phase 7: Save / Load / Print / New */
                                                                                                                                                                                      const STORAGE_KEY='room-planner-v7';

                                                                                                                                                                                      function newRoom(){
                                                                                                                                                                                        if(!confirm('Start a new layout? This will clear everything.'))return;
                                                                                                                                                                                          shapes=[];labels=[];strokes=[];
                                                                                                                                                                                            room=defaultRoom(canvas.width,canvas.height);
                                                                                                                                                                                              selectedShape=null;selectedLabel=null;
                                                                                                                                                                                                editMode=false;
                                                                                                                                                                                                  document.getElementById('btn-edit-room').classList.remove('active');
                                                                                                                                                                                                    clearAllTools();
                                                                                                                                                                                                      zoom=1;panX=0;panY=0;
                                                                                                                                                                                                        updateZoomLabel();
                                                                                                                                                                                                          updateSelectionUI();
                                                                                                                                                                                                            localStorage.removeItem(STORAGE_KEY);
                                                                                                                                                                                                              resetSaveBtn();
                                                                                                                                                                                                                draw();
                                                                                                                                                                                                                }

                                                                                                                                                                                                                function saveRoom(){
                                                                                                                                                                                                                  try{
                                                                                                                                                                                                                      const payload={room:cornersToFractions(room,canvas.width,canvas.height),shapes,labels,strokes,zoom,panX,panY,savedAt:Date.now()};
                                                                                                                                                                                                                          localStorage.setItem(STORAGE_KEY,JSON.stringify(payload));
                                                                                                                                                                                                                              resetSaveBtn();
                                                                                                                                                                                                                                  flashSaveButton();
                                                                                                                                                                                                                                    }catch(e){console.warn('Save failed:',e);alert('Could not save — storage may be full.');}
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    function loadRoom(){
                                                                                                                                                                                                                                      try{
                                                                                                                                                                                                                                          const raw=localStorage.getItem(STORAGE_KEY);
                                                                                                                                                                                                                                              if(!raw)return;
                                                                                                                                                                                                                                                  const data=JSON.parse(raw);
                                                                                                                                                                                                                                                      if(data.room&&data.room.length===4)room=fractionsToCorners(data.room,canvas.width,canvas.height);
                                                                                                                                                                                                                                                          if(data.shapes&&Array.isArray(data.shapes))shapes=data.shapes.map(s=>({angle:0,fill:'#ffffff',...s}));
                                                                                                                                                                                                                                                              if(data.labels&&Array.isArray(data.labels))labels=data.labels.map(l=>({fontSize:16,colour:'#222222',bold:false,...l}));
                                                                                                                                                                                                                                                                  if(data.strokes&&Array.isArray(data.strokes))strokes=data.strokes;
                                                                                                                                                                                                                                                                      if(data.zoom){zoom=data.zoom;panX=data.panX||0;panY=data.panY||0;}
                                                                                                                                                                                                                                                                          hasUnsavedChanges=false;
                                                                                                                                                                                                                                                                              updateZoomLabel();
                                                                                                                                                                                                                                                                                }catch(e){console.warn('Load failed:',e);}
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                function flashSaveButton(){
                                                                                                                                                                                                                                                                                  const btn=document.getElementById('btn-save');
                                                                                                                                                                                                                                                                                    btn.textContent='Saved \u2713';
                                                                                                                                                                                                                                                                                      btn.style.color='#1a73e8';
                                                                                                                                                                                                                                                                                        btn.style.fontWeight='700';
                                                                                                                                                                                                                                                                                          btn.style.borderColor='#1a73e8';
                                                                                                                                                                                                                                                                                            setTimeout(()=>{btn.textContent='Save';btn.style.color='';btn.style.fontWeight='';btn.style.borderColor='';},2000);
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            function printRoom(){
                                                                                                                                                                                                                                                                                              selectedShape=null;selectedLabel=null;
                                                                                                                                                                                                                                                                                                updateSelectionUI();clearAllTools();draw();
                                                                                                                                                                                                                                                                                                  const dataURL=canvas.toDataURL('image/png');
                                                                                                                                                                                                                                                                                                    const printWin=window.open('','_blank','width=900,height=700');
                                                                                                                                                                                                                                                                                                      if(!printWin){window.print();return;}
                                                                                                                                                                                                                                                                                                        printWin.document.write('<!DOCTYPE html><html><head><title>Room Planner</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{background:#fff;display:flex;flex-direction:column;min-height:100vh;}img{display:block;width:100%;height:auto;max-height:92vh;object-fit:contain;}footer{text-align:center;font-size:11px;color:#aaa;font-family:sans-serif;padding:6px;margin-top:auto;}@media print{footer{display:block;}}</style></head><body><img src="'+dataURL+'" /><footer>Designed by Ben &mdash; Room Planner</footer><script>window.onload=function(){window.print();}<\/script></body></html>');
                                                                                                                                                                                                                                                                                                          printWin.document.close();
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                          if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
                                                                                                                                                                                                                                                                                                          })();